config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/OphidiaBigData/ophidia-workflow-catalogue:
      branch: master
      repo: https://github.com/OphidiaBigData/ophidia-workflow-catalogue
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-gold-clam.sh
        container: qc.acc_snappy-xanthic-cichlid
  QC.Doc:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-coral-gharial.sh
        container: qc.doc_crabby-azure-spaniel
      github.com/OphidiaBigData/ophidia-workflow-catalogue git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-eggplant-lionfish.sh
        container: qc.doc_nerdy-teal-maltese
      github.com/OphidiaBigData/ophidia-workflow-catalogue markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-chocolate-squid.sh
        container: qc.doc_trippy-flax-uakari
  QC.Lic:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-flax-ant.sh
        container: qc.lic_baggy-turquoise-rottweiler
  QC.Sec:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-ecru-fly.sh
        container: qc.sec_paltry-linen-monster
  QC.Sty:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue find_oph_workflows.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-harlequin-clam.sh
        container: qc.sty_gloppy-zucchini-serval
  QC.Uni:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-white-weasel.sh
        container: qc.uni_hasty-cobalt-bordeaux
  QC.Ver:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-magnolia-sparrow.sh
        container: qc.ver_cranky-brown-devil
timeout: 5400
