config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/OphidiaBigData/ophidia-workflow-catalogue:
      branch: master
      repo: https://github.com/OphidiaBigData/ophidia-workflow-catalogue
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Sty:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue find_oph_workflows.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-carmine-kiwi.sh
        container: qc.sty_stealthy-cobalt-civet
timeout: 5400
