config:
  credentials:
  - id: https://github.com/OphidiaBigData/ophidia-workflow-catalogue
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/OphidiaBigData/ophidia-workflow-catalogue:
      branch: master
      credential_tmp: true
      credentials_id: https://github.com/OphidiaBigData/ophidia-workflow-catalogue
      repo: https://github.com/OphidiaBigData/ophidia-workflow-catalogue
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue git:
        commands:
        - /usr/bin/env sh .sqa/script.sapphire_passionate_hornbill.sh
        container: qc.acc_pumpkin_wise_lionfish
  QC.Doc:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.orchid_lively_orangutan.sh
        container: qc.doc_currant_affectionate_octopus
      github.com/OphidiaBigData/ophidia-workflow-catalogue git:
        commands:
        - /usr/bin/env sh .sqa/script.scarlet_reckless_elk.sh
        container: qc.doc_echelon_radiant_clownfish
      github.com/OphidiaBigData/ophidia-workflow-catalogue markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dahlia_melancholy_swan.sh
        container: qc.doc_glacier_optimistic_catfish
  QC.Lic:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue licensee:
        commands:
        - /usr/bin/env sh .sqa/script.salmon_generous_pelican.sh
        container: qc.lic_hunter_fearless_clownfish
  QC.Sec:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gold_resilient_boa.sh
        container: qc.sec_lagoon_dedicated_marmoset
  QC.Sty:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cerulean_romantic_gorilla.sh
        container: qc.sty_prussian_brilliant_whale
      github.com/OphidiaBigData/ophidia-workflow-catalogue jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.green_scrappy_sphinx.sh
        container: qc.sty_yellow_supportive_ferret
      github.com/OphidiaBigData/ophidia-workflow-catalogue pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.iris_nurturing_kirin.sh
        container: qc.sty_orchid_vibrant_spren
  QC.Uni:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue pytest:
        commands:
        - /usr/bin/env sh .sqa/script.incarnadine_courageous_boa.sh
        container: qc.uni_chartreuse_imaginative_orca
  QC.Ver:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.espresso_driven_tortoise.sh
        container: qc.ver_teal_sympathetic_kangaroo
timeout: 5400
