config:
  credentials:
  - id: https://github.com/OphidiaBigData/ophidia-workflow-catalogue
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/OphidiaBigData/ophidia-workflow-catalogue:
      branch: master
      credential_tmp: true
      credentials_id: https://github.com/OphidiaBigData/ophidia-workflow-catalogue
      repo: https://github.com/OphidiaBigData/ophidia-workflow-catalogue
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue git:
        commands:
        - /usr/bin/env sh .sqa/script.prussian_bewildered_wombat.sh
        container: qc.acc_coffee_organized_reindeer
  QC.Doc:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smoke_proactive_serval.sh
        container: qc.doc_pumpkin_gracious_jellyfish
      github.com/OphidiaBigData/ophidia-workflow-catalogue git:
        commands:
        - /usr/bin/env sh .sqa/script.green_persistent_lionfish.sh
        container: qc.doc_cinnabar_balanced_mongoose
      github.com/OphidiaBigData/ophidia-workflow-catalogue markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gray_warm_elk.sh
        container: qc.doc_cinnabar_tenacious_kraken
  QC.Lic:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sienna_aware_roadrunner.sh
        container: qc.lic_wisteria_open_panther
  QC.Sec:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ultramarine_daring_mink.sh
        container: qc.sec_apricot_apathetic_unicorn
  QC.Sty:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue flake8:
        commands:
        - /usr/bin/env sh .sqa/script.burgundy_reserved_spider.sh
        container: qc.sty_zinnia_authentic_porcupine
      github.com/OphidiaBigData/ophidia-workflow-catalogue jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.porcelain_eccentric_reindeer.sh
        container: qc.sty_turmeric_artistic_octopus
      github.com/OphidiaBigData/ophidia-workflow-catalogue pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.lavender_bewildered_nymph.sh
        container: qc.sty_copper_fearless_peacock
  QC.Uni:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue pytest:
        commands:
        - /usr/bin/env sh .sqa/script.echelon_skeptical_tarantula.sh
        container: qc.uni_magenta_radiant_peacock
  QC.Ver:
    repos:
      github.com/OphidiaBigData/ophidia-workflow-catalogue get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pumpkin_perky_wolverine.sh
        container: qc.ver_periwinkle_meticulous_tortoise
timeout: 5400
